### ISSUE TITLE
Tasks have duplicated variables if they use the same variable name as the previous task in the workflow

### ISSUE THREAD

**Issue by brosenberg42** [smart-cow/scow#76] opened 2014-06-06 15:02 UTC
![moo](https://cloud.githubusercontent.com/assets/5748179/3201796/7bfb87d4-ed8b-11e3-822b-aa81be44bee3.PNG)

![moo](https://cloud.githubusercontent.com/assets/5748179/3201798/95176c24-ed8b-11e3-91be-e2009bc2289e.PNG)

**Comment by jkranes** [comment] 2014-06-23 13:20
I believe this is caused by sending non modifiable variables to the server.  These are then treated as new ad-hoc variables.   To get this working correctly I need to push the latest server code and then we need to modify the webapp so that it looks at the variable "modifiable" attibute and does not send the variable if it is false.

**Comment by brosenberg42** [comment] 2014-06-23 13:53
@jkranes are you adding a property called modifiable to the variable object, or is it deducible from the current properties of a variable?

**Comment by jkranes** [comment] 2014-06-23 13:58
@brosenberg42: There will be a new property. This is already coded but not
yet merged in. There is also a "required" property that indicates that a
value MUST be provided.

**Comment by lewisloren** [comment] 2014-07-01 14:10
waiting to see if Jon's other changes in the use of variables will indirectly fix this problem.

**Closed as completed** 2017-05-08 14:40 UTC
